services:
  db:
    container_name: system-design-db
    image: postgres
    environment:
      POSTGRES_USER: sys_user
      POSTGRES_PASSWORD: TestPass2023
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db:

