server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/system_design_db
    username: sys_user
    password: TestPass2023
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect